name: AlanSuperstar
favicon: null
layout_spectrum: 0.8605338886845857
typography_spectrum: 0.5046154549345374
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9447406467515975
  lightness: 0.24069213983602822
  saturation: 0.4308641899842769
  rhythmicContrast: 0.21624673157930374
purpose: []
